### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by im-code** [th0rex/pe_load#1]
Hi! Could you help me?
error: process didn't exit successfully: `target\debug\pe_load.exe` (exit code: 3221225477)
Process finished with exit code -1073741819 (0xC0000005)

host: x86_64-pc-windows-gnu

**Comment by th0rex** [comment]
You probably shouldn't use this, I only tested it on simple cases and I don't need it anymore so I stopped developing it.

I can't really tell what the problem is from just looking at that. IIRC that exit code happens when an access violation happens.

If my memory serves me right I haven't implemented initialization of static variables so anything but the most trivial programs won't work.

You could try writing (or generating) bindings to some c++ or c library that can load PE files.

**Comment by im-code** [comment]
I understood. Thank you for answers!
